// <auto-generated />
namespace ByteCore.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class User_Logging_Id_Fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Logging_Id_Fix));
        
        string IMigrationMetadata.Id
        {
            get { return "202505072124098_User_Logging_Id_Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
