// <auto-generated />
namespace ByteCore.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Section_Quiz_Optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Section_Quiz_Optional));
        
        string IMigrationMetadata.Id
        {
            get { return "202504162334382_Section_Quiz_Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
