namespace ByteCore.BusinessLogic.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Added_Data_Annotations : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.Quizs", newName: "Quizzes");
            RenameTable(name: "dbo.ChapterUsers", newName: "UserChapters");
            DropForeignKey("dbo.LoginLogs", "User_Id", "dbo.Users");
            DropForeignKey("dbo.Sections", "Chapter_Id", "dbo.Chapters");
            DropForeignKey("dbo.Questions", "Quiz_Id", "dbo.Quizs");
            DropForeignKey("dbo.QuestionOptions", "Question_Id", "dbo.Questions");
            DropForeignKey("dbo.QuizResultAnswers", "Question_Id", "dbo.Questions");
            DropForeignKey("dbo.QuizResultAnswers", "QuizResult_Id", "dbo.QuizResults");
            DropForeignKey("dbo.QuizResults", "Quiz_Id", "dbo.Quizs");
            DropForeignKey("dbo.QuizResults", "User_Id", "dbo.Users");
            DropForeignKey("dbo.UserSessions", "User_Id", "dbo.Users");
            DropIndex("dbo.Sections", new[] { "Chapter_Id" });
            DropIndex("dbo.Questions", new[] { "Quiz_Id" });
            DropIndex("dbo.QuestionOptions", new[] { "Question_Id" });
            DropIndex("dbo.LoginLogs", new[] { "User_Id" });
            DropIndex("dbo.QuizResultAnswers", new[] { "Question_Id" });
            DropIndex("dbo.QuizResultAnswers", new[] { "QuizResult_Id" });
            DropIndex("dbo.QuizResults", new[] { "Quiz_Id" });
            DropIndex("dbo.QuizResults", new[] { "User_Id" });
            DropIndex("dbo.UserSessions", new[] { "User_Id" });
            RenameColumn(table: "dbo.LoginLogs", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.Sections", name: "Chapter_Id", newName: "ChapterId");
            RenameColumn(table: "dbo.Questions", name: "Quiz_Id", newName: "QuizId");
            RenameColumn(table: "dbo.QuestionOptions", name: "Question_Id", newName: "QuestionId");
            RenameColumn(table: "dbo.QuizResultAnswers", name: "Question_Id", newName: "QuestionId");
            RenameColumn(table: "dbo.QuizResultAnswers", name: "QuizResult_Id", newName: "QuizResultId");
            RenameColumn(table: "dbo.QuizResults", name: "Quiz_Id", newName: "QuizId");
            RenameColumn(table: "dbo.QuizResults", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.UserSessions", name: "User_Id", newName: "UserId");
            DropPrimaryKey("dbo.UserChapters");
            AlterColumn("dbo.AuditLogs", "ControllerName", c => c.String(maxLength: 100));
            AlterColumn("dbo.AuditLogs", "ActionName", c => c.String(maxLength: 100));
            AlterColumn("dbo.AuditLogs", "HttpMethod", c => c.String(maxLength: 10));
            AlterColumn("dbo.AuditLogs", "IpAddress", c => c.String(maxLength: 45));
            AlterColumn("dbo.Users", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Users", "Email", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Users", "Password", c => c.String(nullable: false));
            AlterColumn("dbo.Users", "Role", c => c.String(maxLength: 50));
            AlterColumn("dbo.Users", "LatestBrowserUsed", c => c.String(maxLength: 200));
            AlterColumn("dbo.Chapters", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Courses", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Courses", "ShortDescription", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("dbo.Courses", "Instructor", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Courses", "ImageUrl", c => c.String(maxLength: 200));
            AlterColumn("dbo.Sections", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Sections", "ChapterId", c => c.Int(nullable: false));
            AlterColumn("dbo.Quizzes", "Title", c => c.String(maxLength: 200));
            AlterColumn("dbo.Questions", "QuizId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuestionOptions", "QuestionId", c => c.Int(nullable: false));
            AlterColumn("dbo.LoginLogs", "IpAddress", c => c.String(maxLength: 45));
            AlterColumn("dbo.LoginLogs", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuizResultAnswers", "QuestionId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuizResultAnswers", "QuizResultId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuizResults", "QuizId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuizResults", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserSessions", "UserId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.UserChapters", new[] { "User_Id", "Chapter_Id" });
            CreateIndex("dbo.Sections", "ChapterId");
            CreateIndex("dbo.Questions", "QuizId");
            CreateIndex("dbo.QuestionOptions", "QuestionId");
            CreateIndex("dbo.LoginLogs", "UserId");
            CreateIndex("dbo.QuizResultAnswers", "QuizResultId");
            CreateIndex("dbo.QuizResultAnswers", "QuestionId");
            CreateIndex("dbo.QuizResults", "QuizId");
            CreateIndex("dbo.QuizResults", "UserId");
            CreateIndex("dbo.UserSessions", "UserId");
            AddForeignKey("dbo.LoginLogs", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Sections", "ChapterId", "dbo.Chapters", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Questions", "QuizId", "dbo.Quizzes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.QuestionOptions", "QuestionId", "dbo.Questions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.QuizResultAnswers", "QuestionId", "dbo.Questions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.QuizResultAnswers", "QuizResultId", "dbo.QuizResults", "Id", cascadeDelete: true);
            AddForeignKey("dbo.QuizResults", "QuizId", "dbo.Quizzes", "Id", cascadeDelete: false);
            AddForeignKey("dbo.QuizResults", "UserId", "dbo.Users", "Id", cascadeDelete: false);
            AddForeignKey("dbo.UserSessions", "UserId", "dbo.Users", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UserSessions", "UserId", "dbo.Users");
            DropForeignKey("dbo.QuizResults", "UserId", "dbo.Users");
            DropForeignKey("dbo.QuizResults", "QuizId", "dbo.Quizzes");
            DropForeignKey("dbo.QuizResultAnswers", "QuizResultId", "dbo.QuizResults");
            DropForeignKey("dbo.QuizResultAnswers", "QuestionId", "dbo.Questions");
            DropForeignKey("dbo.QuestionOptions", "QuestionId", "dbo.Questions");
            DropForeignKey("dbo.Questions", "QuizId", "dbo.Quizzes");
            DropForeignKey("dbo.Sections", "ChapterId", "dbo.Chapters");
            DropForeignKey("dbo.LoginLogs", "UserId", "dbo.Users");
            DropIndex("dbo.UserSessions", new[] { "UserId" });
            DropIndex("dbo.QuizResults", new[] { "UserId" });
            DropIndex("dbo.QuizResults", new[] { "QuizId" });
            DropIndex("dbo.QuizResultAnswers", new[] { "QuestionId" });
            DropIndex("dbo.QuizResultAnswers", new[] { "QuizResultId" });
            DropIndex("dbo.LoginLogs", new[] { "UserId" });
            DropIndex("dbo.QuestionOptions", new[] { "QuestionId" });
            DropIndex("dbo.Questions", new[] { "QuizId" });
            DropIndex("dbo.Sections", new[] { "ChapterId" });
            DropPrimaryKey("dbo.UserChapters");
            AlterColumn("dbo.UserSessions", "UserId", c => c.Int());
            AlterColumn("dbo.QuizResults", "UserId", c => c.Int());
            AlterColumn("dbo.QuizResults", "QuizId", c => c.Int());
            AlterColumn("dbo.QuizResultAnswers", "QuizResultId", c => c.Int());
            AlterColumn("dbo.QuizResultAnswers", "QuestionId", c => c.Int());
            AlterColumn("dbo.LoginLogs", "UserId", c => c.Int());
            AlterColumn("dbo.LoginLogs", "IpAddress", c => c.String());
            AlterColumn("dbo.QuestionOptions", "QuestionId", c => c.Int());
            AlterColumn("dbo.Questions", "QuizId", c => c.Int());
            AlterColumn("dbo.Quizzes", "Title", c => c.String());
            AlterColumn("dbo.Sections", "ChapterId", c => c.Int());
            AlterColumn("dbo.Sections", "Title", c => c.String());
            AlterColumn("dbo.Courses", "ImageUrl", c => c.String());
            AlterColumn("dbo.Courses", "Instructor", c => c.String());
            AlterColumn("dbo.Courses", "ShortDescription", c => c.String());
            AlterColumn("dbo.Courses", "Title", c => c.String());
            AlterColumn("dbo.Chapters", "Title", c => c.String());
            AlterColumn("dbo.Users", "LatestBrowserUsed", c => c.String());
            AlterColumn("dbo.Users", "Role", c => c.String());
            AlterColumn("dbo.Users", "Password", c => c.String());
            AlterColumn("dbo.Users", "Email", c => c.String());
            AlterColumn("dbo.Users", "Name", c => c.String());
            AlterColumn("dbo.AuditLogs", "IpAddress", c => c.String());
            AlterColumn("dbo.AuditLogs", "HttpMethod", c => c.String());
            AlterColumn("dbo.AuditLogs", "ActionName", c => c.String());
            AlterColumn("dbo.AuditLogs", "ControllerName", c => c.String());
            AddPrimaryKey("dbo.UserChapters", new[] { "Chapter_Id", "User_Id" });
            RenameColumn(table: "dbo.UserSessions", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.QuizResults", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.QuizResults", name: "QuizId", newName: "Quiz_Id");
            RenameColumn(table: "dbo.QuizResultAnswers", name: "QuizResultId", newName: "QuizResult_Id");
            RenameColumn(table: "dbo.QuizResultAnswers", name: "QuestionId", newName: "Question_Id");
            RenameColumn(table: "dbo.QuestionOptions", name: "QuestionId", newName: "Question_Id");
            RenameColumn(table: "dbo.Questions", name: "QuizId", newName: "Quiz_Id");
            RenameColumn(table: "dbo.Sections", name: "ChapterId", newName: "Chapter_Id");
            RenameColumn(table: "dbo.LoginLogs", name: "UserId", newName: "User_Id");
            CreateIndex("dbo.UserSessions", "User_Id");
            CreateIndex("dbo.QuizResults", "User_Id");
            CreateIndex("dbo.QuizResults", "Quiz_Id");
            CreateIndex("dbo.QuizResultAnswers", "QuizResult_Id");
            CreateIndex("dbo.QuizResultAnswers", "Question_Id");
            CreateIndex("dbo.LoginLogs", "User_Id");
            CreateIndex("dbo.QuestionOptions", "Question_Id");
            CreateIndex("dbo.Questions", "Quiz_Id");
            CreateIndex("dbo.Sections", "Chapter_Id");
            AddForeignKey("dbo.UserSessions", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.QuizResults", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.QuizResults", "Quiz_Id", "dbo.Quizs", "Id");
            AddForeignKey("dbo.QuizResultAnswers", "QuizResult_Id", "dbo.QuizResults", "Id");
            AddForeignKey("dbo.QuizResultAnswers", "Question_Id", "dbo.Questions", "Id");
            AddForeignKey("dbo.QuestionOptions", "Question_Id", "dbo.Questions", "Id");
            AddForeignKey("dbo.Questions", "Quiz_Id", "dbo.Quizs", "Id");
            AddForeignKey("dbo.Sections", "Chapter_Id", "dbo.Chapters", "Id");
            AddForeignKey("dbo.LoginLogs", "User_Id", "dbo.Users", "Id");
            RenameTable(name: "dbo.UserChapters", newName: "ChapterUsers");
            RenameTable(name: "dbo.Quizzes", newName: "Quizs");
        }
    }
}
