// <auto-generated />
namespace ByteCore.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Audit_Login_Logging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Audit_Login_Logging));
        
        string IMigrationMetadata.Id
        {
            get { return "202505072045519_Audit_Login_Logging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
